server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE


#ADDED TO BOOTSTRAP FILE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://172.17.0.4:8761/eureka/
  instance:
    hostname: localhost